version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-container
    
  redis-container:
    image: redis
    expose:
      - 6379

